package com.dawood.nggeen.shared.dto;

public enum ErrorCode {

    MARKET_NOT_TRADING("MARKET_NOT_TRADING"),
    ORDER_EXECUTION_FAILED("ORDER_EXECUTION_FAILED"),
    INVALID_SYMBOL("INVALID_SYMBOL"),
    INSTRUMENT_NOT_FOUND("INSTRUMENT_NOT_FOUND"),
    INVALID_QUANTITY("INVALID_QUANTITY"),
    QUANTITY_BELOW_MINIMUM("QUANTITY_BELOW_MINIMUM"),
    QUANTITY_EXCEEDS_MAXIMUM("QUANTITY_EXCEEDS_MAXIMUM"),
    QUANTITY_PRECISION_EXCEEDED("QUANTITY_PRECISION_EXCEEDED"),
    LOT_SIZE_STEP_MISMATCH("LOT_SIZE_STEP_MISMATCH"),
    INVALID_PRICE("INVALID_PRICE"),
    PRICE_PRECISION_EXCEEDED("PRICE_PRECISION_EXCEEDED"),
    PRICE_TICK_SIZE_MISMATCH("PRICE_TICK_SIZE_MISMATCH"),
    MIN_NOTIONAL_NOT_MET("MIN_NOTIONAL_NOT_MET"),
    MAX_NOTIONAL_EXCEEDED("MAX_NOTIONAL_EXCEEDED"),

    BAD_REQUEST("BAD_REQUEST"),
    INVALID_REQUEST("INVALID_REQUEST"),

    INSUFFICIENT_LIQUIDITY("INSUFFICIENT_LIQUIDITY"),

    NOT_FOUND("NOT_FOUND"),

    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR");

    private String code;

    ErrorCode(String code) {
        this.code = code;
    }
}
