server:
  servlet:
    context-path: /api/v1
spring:
  application:
    name: nggeen

  config:
    import: file:.env[.properties]

  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/nggeen-db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: ${SMTP_HOST}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: password
    listener:
      simple:
        retry:
          enabled: true
          max-retries: 3
          initial-interval: 2000ms # Wait 2 seconds before retry 1
          multiplier: 2 #

nggeen:
  journal:
    path: ./data/chronicle/journal
  snapshot:
    path: ./data/snapshots
  security:
    cookie:
      secure: false
    cloud-fare:
      turnstile:
        secret-key: 1x0000000000000000000000000000000AA
#        secret-key: 2x0000000000000000000000000000000AA
#        secret-key: ${CLOUDFARE_TURNSTILE_SECRET_KEY}
    secret-key: ${SECRET_KEY}
    session:
      cleanup:
        retention-days: 30
        batch: 1000
  message:
    mail-sub: ${EMAIL_SUB}
  outbox:
    poller:
      fixed-delay: 2000
      batch-size: 50
  client:
    url: http://localhost:3000/
