server:
  servlet:
    context-path: /api/v1
spring:
  application:
    name: nggeen
  config:
    import: file:.env[.properties]
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/nggeen-db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

nggeen:
  journal:
    path: ./data/chronicle/journal
  snapshot:
    path: ./data/snapshots
  security:
    secret-key: ${SECRET_KEY}
  message:
    mail-sub: ${EMAIL_SUB}